version: '2'
services:
  elasticsearch5:
    restart: always
    image: elasticsearch:5.0
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      # ES_HOME: /eshome
      # ES_HEAP_SIZE: 1g
    volumes:
      - $PWD/esdata:/data
      # - $PWD/elasticsearch:/eshome/config
      - $PWD/elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
    ports:
      - 9210:9200
    logging:
      driver: "json-file"
      # driver: "syslog"
      # options:
      #   syslog-address: "udp://localhost:5140"
    command: ["elasticsearch", "-Epath.conf=/etc/elasticsearch"]

  # localhost -> elasticsearch
  fluent-forward5:
    restart: always
    image: fluent-es
    links:
      - elasticsearch5:elasticsearch
    ports:
      - 5150:5140/udp
      - 24234:24224/tcp
      - 24234:24224/udp
    volumes:
      - $PWD/fluent/fluent-debug.conf:/fluentd/etc/fluent.conf
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:5140"


  # kibana
  kibana5:
    restart: always
    image: kibana:5.0
    ports:
      - 5611:5601
    links:
      - elasticsearch5:elasticsearch
    container_name: kibana
    logging:
      driver: "none"

# cron curastor
# elasticsearch-curator:
#   restart: always
#   image: elasticsearch-curator:4.1
#   volumes:
#     - $PWD/curator/curator:/apps
#     - $PWD/curator/cron:/cron
#   command: ["sh", "/apps/start.sh"]
#   log_opt:
#     syslog-address: "udp://localhost:5140"
